name: Report Binsize Treemap
# yamllint disable rule:line-length
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
jobs:
  report-binsize-treemap:
    name: Report Binsize Treemap
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Fixup git permissions
        # https://github.com/actions/checkout/issues/766
        shell: bash
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Install go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version-file: "go.mod"
          cache: true
          cache-dependency-path: go.sum

      - name: Create Binsize Report
        run: make caph report-binsize-treemap-all

      - name: Upload Report
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: reports-${{ github.sha }}
          path: .reports
          retention-days: 90